### ISSUE TITLE
求支持server2019!

### ISSUE THREAD

**Issue by Keyezi** [dylanbai8/kmspro#6]
谢谢！

**Comment by dylanbai8** [comment]
本来就支持的。按照教程操作激活即可。

**Comment by Keyezi** [comment]
还是不可以 你加下我Q1195557458 我发图给你

**Comment by dylanbai8** [comment]
https://v0v.bid/kms.html
5.激活失败如何排错

**Comment by dylanbai8** [comment]
尝试使用本站提供的其它线路激活
https://v0v.bid/more.html

**Comment by dylanbai8** [comment]
部分idc商家的服务器系统确实会遇到无法使用外网kms激活的问题（如：景安），可以尝试更换安装镜像，或者联系idc客服为你激活。

**Comment by dylanbai8** [comment]
使用图床Markdown代码可以在此处贴图反馈截图。
https://sm.ms/

![2.jpg](https://i.loli.net/2019/08/14/TaP5cMt1k2ORVLJ.jpg)

**Comment by dylanbai8** [comment]
到微软官方 查询 排查激活错误代码：
https://docs.microsoft.com/zh-cn/windows-server/get-started/activation-error-codes

**Comment by Keyezi** [comment]
![Snipaste_2019-08-15_17-50-11.png](https://i.loli.net/2019/08/15/ayq975XN8uvbw1z.png)
并没有出错代码 就是没有产品

**Comment by dylanbai8** [comment]
数据中心版操作系统激活 需要先开放防火墙
教程不严谨 感谢持续反馈
以下激活代码 逐行执行：

```
netsh firewall set icmpsetting 8

slmgr /ipk WMDGN-G9PQG-XVVXX-R3X43-63DFG

slmgr /skms kms.v0v.bid

slmgr /ato
```

**Comment by dylanbai8** [comment]
netsh firewall set icmpsetting 8 -- 开启ICMP回显（即 打开ping）

**Comment by Keyezi** [comment]
现在还有个问题，就是office无法激活 用的Office安装包 和一键激活脚本 目录 服务器都没问题 就是不能激活

**Comment by dylanbai8** [comment]
感谢反馈！由于kms服务器机主近期升级服务器（禁ping），导致一键脚本失效（基于ping检测服务器可用性）。正在逐步修复bat脚本。
命令行激活方式不受影响，暂时请按照教程使用命令行方式激活Windows和office。

**Comment by dylanbai8** [comment]
脚本已修复，请重新下载使用。
